#!/usr/bin/env bash
# Create the three k3d clusters.
#
# Ingredient 2 of 3 for the flat network: each cluster gets its own pod and
# service CIDR. k3s defaults every cluster to 10.42.0.0/16 pods / 10.43.0.0/16
# services; if two clusters share that, a pod IP is ambiguous and cross-cluster
# routing cannot work at all.
#
# Config files are generated from the topology table in lib.sh rather than
# checked in, so the table stays the single source of truth.

. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

need docker k3d kubectl jq

GEN_DIR="${REPO_ROOT}/clusters/.generated"
mkdir -p "$GEN_DIR"

# Zone and region labels, one node per zone: the first zone goes on the server,
# which stays schedulable rather than tainted, and each zone after that on an
# agent. Generated from the cluster's own region rather than written out: zones
# are region-scoped, so east and central share region-a's zones while west has
# region-b's. Hardcoding them once meant a zone label that spanned two regions.
zone_labels() {
  local name="$1" region z i=0 filter
  region="$(cluster_region "$name")"
  for z in $(zones_for "$name"); do
    if [ "$i" = "0" ]; then filter="server:0"; else filter="agent:$(( i - 1 ))"; fi
    printf '      - label: topology.kubernetes.io/zone=%s\n        nodeFilters: [%s]\n' "$z" "$filter"
    printf '      - label: topology.kubernetes.io/region=%s\n        nodeFilters: [%s]\n' "$region" "$filter"
    i=$(( i + 1 ))
  done
}

gen_config() {
  local name="$1"
  local pod_cidr svc_cidr
  pod_cidr="$(cluster_pod_cidr "$name")"
  svc_cidr="$(cluster_svc_cidr "$name")"

  cat > "${GEN_DIR}/${name}.yaml" <<EOF
# GENERATED by clusters/01-create-clusters.sh -- edit clusters/lib.sh instead.
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ${name}
servers: 1
agents: $(( $(zone_count) - 1 ))
image: ${K3S_IMAGE}
network: ${DOCKER_NET}
options:
  k3d:
    # No k3d loadbalancer container: we reach services via port-forward and
    # cross-cluster traffic goes pod-to-pod. Saves one container per cluster.
    disableLoadbalancer: true
  k3s:
    extraArgs:
      # servicelb (klipper-lb) is deliberately KEPT: the Linkerd multicluster
      # gateway Service is type LoadBalancer, and without a LB controller it
      # sits Pending forever. Overriding it to NodePort desynchronizes the
      # gateway probe (the mirrored probe Service still publishes 4191 while
      # the endpoint points at the nodePort), so the gateway link never goes
      # healthy. klipper-lb assigns node IPs as EXTERNAL-IPs, and those are on
      # the shared Docker network -- so they are reachable cross-cluster.
      #
      # metrics-server is also KEPT: FM1b (identity down blocks scale-up)
      # needs real HPA behaviour.
      - arg: --disable=traefik,local-storage
        nodeFilters: [server:*]
      - arg: --cluster-cidr=${pod_cidr}
        nodeFilters: [server:*]
      - arg: --service-cidr=${svc_cidr}
        nodeFilters: [server:*]
    nodeLabels:
$(zone_labels "$name")
EOF
}

api_ready() {
  kubectl --context="$(ctx "$1")" cluster-info >/dev/null 2>&1
}

dns_ready() {
  local c="$(ctx "$1")"
  local n
  n="$(kubectl --context="$c" get po -n kube-system -l k8s-app=kube-dns \
        -o json 2>/dev/null | jq '.items | length')"
  [ "${n:-0}" != "0" ] || return 1
  kubectl --context="$c" wait pod \
    --for=condition=ready --namespace=kube-system \
    --selector=k8s-app=kube-dns --timeout=90s >/dev/null 2>&1
}

for name in $(clusters); do
  if k3d cluster list "$name" >/dev/null 2>&1; then
    log "cluster '${name}' already exists, skipping create"
  else
    gen_config "$name"
    log "creating cluster '${name}' (region $(cluster_region "$name"), pods $(cluster_pod_cidr "$name"))"
    k3d cluster create -c "${GEN_DIR}/${name}.yaml" --kubeconfig-update-default
  fi

  retry 12 10 api_ready "$name" || die "cluster '${name}': API server never became ready"
  retry 18 5  dns_ready "$name" || die "cluster '${name}': CoreDNS never became ready"
  ok "cluster '${name}' up"
done

log "cluster inventory"
k3d cluster list

log "node topology"
for name in $(clusters); do
  printf '\n--- %s (%s) ---\n' "$name" "$(cluster_region "$name")"
  kubectl --context="$(ctx "$name")" get nodes \
    -L topology.kubernetes.io/zone,topology.kubernetes.io/region \
    -o custom-columns='NODE:.metadata.name,POD_CIDR:.spec.podCIDR,IP:.status.addresses[?(@.type=="InternalIP")].address,ZONE:.metadata.labels.topology\.kubernetes\.io/zone'
done
