#!/usr/bin/env bash
# Install Linkerd on all three clusters, sharing one trust anchor.
#
# Dual mode:
#   LINKERD_FLAVOR=oss  (default) -- open source Linkerd. Covers FM1/FM2/FM4/FM5
#                                    arms 1-2. No license needed.
#   LINKERD_FLAVOR=bel            -- Buoyant Enterprise for Linkerd. Adds HAZL
#                                    (FM3 brownout) and the 2.20 trust anchor
#                                    rotation operator (FM5 arm 3). Needs a
#                                    license in $BUOYANT_LICENSE.
#
# Every cluster gets the SAME root.crt (trust anchor) and its OWN issuer. That
# shared anchor is what makes cross-cluster mTLS possible -- and what makes it a
# single global failure domain.

. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

need kubectl

CERT_DIR="${REPO_ROOT}/certs"
[ -f "${CERT_DIR}/root.crt" ] || die "no trust anchor: run clusters/03-certs.sh first"

# linkerd install --crds refuses to run without these. Pinned deliberately;
# bumping it is a conscious decision, not a drive-by.
GATEWAY_API_VERSION="${GATEWAY_API_VERSION:-v1.2.1}"
GATEWAY_API_URL="https://github.com/kubernetes-sigs/gateway-api/releases/download/${GATEWAY_API_VERSION}/standard-install.yaml"

install_gateway_api() {
  local c="$1"
  if kubectl --context="$c" get crd httproutes.gateway.networking.k8s.io >/dev/null 2>&1; then
    log "  gateway api crds already present"
    return
  fi
  log "  installing gateway api crds (${GATEWAY_API_VERSION})"
  kubectl --context="$c" apply --server-side -f "$GATEWAY_API_URL" >/dev/null
}

# --- flavor selection -------------------------------------------------------

case "$LINKERD_FLAVOR" in
  oss)
    need linkerd
    if linkerd version --client 2>/dev/null | grep -qi enterprise; then
      die "LINKERD_FLAVOR=oss but the linkerd CLI on PATH is the enterprise build.
Reinstall the OSS CLI (curl -sL https://run.linkerd.io/install | sh) or set LINKERD_FLAVOR=bel."
    fi
    ;;
  bel)
    # lib.sh already sourced settings.local.sh, stripped any wrapping whitespace
    # from the license, and put the enterprise CLI first on PATH.
    need helm kubectl linkerd
    [ -n "${BUOYANT_LICENSE:-}" ] || die "LINKERD_FLAVOR=bel needs a license.

Get a trial at https://enterprise.buoyant.io, then:
  echo 'export BUOYANT_LICENSE=\"<your-key>\"' >> ${REPO_ROOT}/settings.local.sh

(settings.local.sh is gitignored.)"

    linkerd version --client 2>/dev/null | grep -qi enterprise || die \
"LINKERD_FLAVOR=bel but the linkerd CLI on PATH is not the enterprise build.
Install it alongside the OSS one:
  INSTALLROOT=\$HOME/.linkerd2-bel curl -sL https://enterprise.buoyant.io/install | sh"
    ;;
  *)
    die "LINKERD_FLAVOR must be 'oss' or 'bel', got '${LINKERD_FLAVOR}'"
    ;;
esac

# BEL is installed with Helm, not with the CLI. There are three charts, and the
# multicluster one matters here: clusters/05-multicluster.sh must use
# linkerd-enterprise-multicluster to match, not the OSS extension.
BEL_REPO="${BEL_REPO:-https://helm.buoyant.cloud}"
BEL_VERSION="${BEL_VERSION:-2.20.1}"   # chart version; appVersion enterprise-2.20.1

install_bel() {
  local name="$1" c values
  c="$(ctx "$name")"
  values="${REPO_ROOT}/clusters/.generated/bel-values-${name}.yaml"
  mkdir -p "$(dirname "$values")"

  helm --kube-context="$c" upgrade --install linkerd-enterprise-crds \
    linkerd-buoyant/linkerd-enterprise-crds \
    --version "$BEL_VERSION" \
    --namespace linkerd --create-namespace \
    --wait --timeout 5m >/dev/null

  # A values file rather than --set: clusterNetworks is a comma-separated list,
  # and helm's --set parser treats commas as value separators. Escaping them
  # works but is fragile; a file sidesteps it entirely.
  #
  # HAZL: without -ext-endpoint-zone-weights the destination controller does not
  # emit the zone weights the proxy balancer needs, and FM3 has nothing to
  # measure. See verify/metrics.md -- the load-average metric only exists here.
  cat > "$values" <<EOF
# GENERATED by clusters/04-linkerd.sh -- edit clusters/lib.sh instead.
clusterNetworks: "$(all_cluster_networks)"
destinationController:
  additionalArgs:
    - -ext-endpoint-zone-weights
EOF

  # HA, spelled out rather than via the chart's ha values file, because the
  # enterprise chart is installed by name from a repo and there is no local
  # values-ha.yaml to -f. These are the settings `linkerd install --ha` applies.
  # See LINKERD_HA in clusters/lib.sh.
  if [ "$LINKERD_HA" = "1" ]; then
    cat >> "$values" <<EOF
controllerReplicas: 3
enablePodAntiAffinity: true
proxy:
  resources:
    cpu:
      request: 100m
    memory:
      limit: 250Mi
      request: 20Mi
EOF
  fi

  # The license goes via --set, not the values file, so it never touches disk.
  helm --kube-context="$c" upgrade --install linkerd-control-plane \
    linkerd-buoyant/linkerd-enterprise-control-plane \
    --version "$BEL_VERSION" \
    --namespace linkerd \
    -f "$values" \
    --set-file identityTrustAnchorsPEM="${CERT_DIR}/root.crt" \
    --set-file identity.issuer.tls.crtPEM="${CERT_DIR}/issuer-${name}.crt" \
    --set-file identity.issuer.tls.keyPEM="${CERT_DIR}/issuer-${name}.key" \
    --set license="$BUOYANT_LICENSE" \
    --wait --timeout 10m >/dev/null
}

install_oss() {
  local name="$1" c networks install_args
  c="$(ctx "$name")"
  # Escape commas: helm --set treats them as value separators.
  networks="$(all_cluster_networks | sed 's/,/\\,/g')"

  install_args="--identity-trust-anchors-file ${CERT_DIR}/root.crt
    --identity-issuer-certificate-file ${CERT_DIR}/issuer-${name}.crt
    --identity-issuer-key-file ${CERT_DIR}/issuer-${name}.key
    --set clusterNetworks=${networks}"

  # See LINKERD_HA in clusters/lib.sh for why this is not academic: without it,
  # FM1 scales a single replica to zero and calls the result "control plane
  # failure", which is not the failure mode anyone running the production
  # checklist would experience.
  if [ "$LINKERD_HA" = "1" ]; then
    install_args="${install_args} --ha"
  fi

  if kubectl --context="$c" get ns linkerd >/dev/null 2>&1; then
    # Idempotent re-run: reconcile an existing install rather than skipping it,
    # so config fixes (like a corrected clusterNetworks) actually land.
    log "  upgrading existing control plane"
    # shellcheck disable=SC2086
    linkerd --context="$c" upgrade $install_args | kubectl --context="$c" apply -f - >/dev/null
  else
    log "  installing crds"
    linkerd --context="$c" install --crds | kubectl --context="$c" apply -f - >/dev/null
    log "  installing control plane"
    # shellcheck disable=SC2086
    linkerd --context="$c" install $install_args | kubectl --context="$c" apply -f - >/dev/null
  fi
}

if [ "$LINKERD_FLAVOR" = "bel" ]; then
  log "installing Buoyant Enterprise for Linkerd ${BEL_VERSION} via Helm"
  helm repo add linkerd-buoyant "$BEL_REPO" >/dev/null 2>&1 || true
  helm repo update linkerd-buoyant >/dev/null 2>&1 || true
else
  log "installing Linkerd OSS (CLI: $(linkerd version --client --short 2>/dev/null || echo unknown))"
fi

# --- install ----------------------------------------------------------------

for name in $(clusters); do
  c="$(ctx "$name")"
  log "cluster '${name}'"

  install_gateway_api "$c"

  if [ "$LINKERD_FLAVOR" = "bel" ]; then
    install_bel "$name"
  else
    install_oss "$name"
  fi

  ok "  control plane applied"
done

# --- wait and check ---------------------------------------------------------

log "waiting for control planes to become ready"
for name in $(clusters); do
  c="$(ctx "$name")"
  kubectl --context="$c" -n linkerd rollout status deploy --timeout=180s >/dev/null 2>&1 \
    || warn "cluster '${name}': some control plane deployments are slow"
done

# `linkerd check` also runs every installed EXTENSION's checks, and those wait
# up to 5 minutes each by default. With three clusters that turns a install
# verification into a 15+ minute stall with no output. Bound it explicitly.
#
# Extension health is verified separately by clusters/07-observability.sh; this
# step only needs to answer "is the core control plane sound?".
CHECK_WAIT="${CHECK_WAIT:-45s}"

failed=0
for name in $(clusters); do
  c="$(ctx "$name")"
  log "linkerd check: ${name} (wait ${CHECK_WAIT})"
  unexpected="$(linkerd_check_unexpected "$c" "$CHECK_WAIT")"
  if [ -z "$unexpected" ]; then
    ok "  ${name} healthy"
  else
    warn "  ${name} check reported unexpected failures:"
    echo "$unexpected" | sed 's/^/    /'
    failed=$((failed + 1))
  fi
done

[ "$failed" -eq 0 ] || die "${failed} cluster(s) failed linkerd check"

# The whole multicluster story depends on this being identical everywhere.
log "verifying the trust anchor is identical across clusters"
anchors=""
for name in $(clusters); do
  fp="$(kubectl --context="$(ctx "$name")" -n linkerd get cm linkerd-identity-trust-roots \
        -o jsonpath='{.data.ca-bundle\.crt}' | openssl x509 -noout -fingerprint -sha256 2>/dev/null \
        | cut -d= -f2)"
  printf '  %-10s %s\n' "$name" "$fp"
  anchors="${anchors}${fp}\n"
done
distinct="$(printf "$anchors" | sort -u | grep -c . || true)"
[ "$distinct" = "1" ] || die "trust anchors DIFFER across clusters -- cross-cluster mTLS will fail"
ok "all clusters share one trust anchor"
