#!/usr/bin/env bash
# Install the multicluster extension and link the clusters together.
#
# We create TWO kinds of link on purpose, because the whole point of the DR
# exercise is that they fail differently:
#
#   pod-to-pod links (--gateway=false), one per ordered cluster pair.
#     These carry both federated services and plain flat mirrors. Requires the
#     flat network from 02-routes.sh.
#
#   gateway links (west -> east and central -> east, both named "east-gw").
#     The classic hierarchical-network mode, kept as a control so a single fault
#     shows a gateway mirror returning 502s while a federated service rebalances
#     cleanly. Mirrored services land as <svc>-east-gw.
#
#     TWO sources, not one, and the second is there for a specific reason: an
#     experiment can only measure a mode the OBSERVING cluster can resolve. west
#     observes FM2, FM3 and FM4; FM1 breaks central's control plane and measures
#     from central. With a gateway link only from west, FM1 had no gateway mirror
#     to compare against and silently tested two modes out of three.
#
# Two k3d-specific wrinkles, both of which bite silently if you miss them:
#
#   1. The kubeconfig server address is https://0.0.0.0:<host-port>, which is
#      meaningless inside a pod. The service-mirror controller runs in a pod, so
#      every link needs --api-server-address pointing at the target's node IP on
#      the shared Docker network.
#
#   2. The gateway Service is type LoadBalancer. k3s's servicelb (klipper-lb) is
#      left enabled precisely so it gets a real EXTERNAL-IP -- the node IPs,
#      which sit on the shared Docker network and are therefore reachable from
#      the other clusters. Do NOT be tempted to override it to NodePort: doing
#      so desynchronizes the gateway probe, because the mirrored probe Service
#      still publishes port 4191 while its endpoint points at the nodePort, and
#      the probe gets "connection reset by peer" forever.

. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

need kubectl linkerd jq

GEN_DIR="${REPO_ROOT}/clusters/.generated"
mkdir -p "$GEN_DIR"

GATEWAY_PORT=4143

# Which gateway-mode links to create, as "source:target".
#
# One per observing cluster, so every experiment can measure all three exposure
# modes from wherever it happens to watch. east needs no gateway link: it is the
# gateway TARGET, and nothing mirrors a cluster to itself.
#
# Keep gateway_target_for in clusters/lib.sh in step with this list.
GATEWAY_LINKS="west:east central:east"

# Linkerd has two independent mirroring modes, each with its own selector:
#
#   --selector                  (default mirror.linkerd.io/exported=true)
#       Gateway mirroring. Traffic hops through the target cluster's gateway.
#
#   --remote-discovery-selector (default mirror.linkerd.io/exported=remote-discovery)
#       Remote discovery, i.e. flat pod-to-pod. Skips the gateway entirely and
#       preserves client identity, so server-side authorization policy still
#       works -- which it cannot through a gateway.
#
# Every link carries BOTH selectors. Left at their defaults, a gatewayless link
# would still try to gateway-mirror anything labelled exported=true, producing
# mirrors with no reachable gateway. So we explicitly point each link's unused
# selector at a label value nothing carries.
DISABLED_SELECTOR="mirror.linkerd.io/exported=none"

# --- helpers ----------------------------------------------------------------

# InternalIP of a cluster's server node, on the shared Docker network. This is
# reachable from any pod in any cluster thanks to the route mesh.
server_ip() {
  kubectl --context="$(ctx "$1")" get node "k3d-$1-server-0" \
    -o jsonpath='{.status.addresses[?(@.type=="InternalIP")].address}'
}

# Links this cluster acts as the SOURCE for. Each needs a controller instance.
links_for_source() {
  local src="$1" dst pair
  for dst in $(clusters); do
    [ "$dst" != "$src" ] || continue
    echo "$dst"
  done
  for pair in $GATEWAY_LINKS; do
    if [ "${pair%%:*}" = "$src" ]; then
      echo "${pair##*:}-gw"
    fi
  done
}

# --- install the extension --------------------------------------------------

for name in $(clusters); do
  c="$(ctx "$name")"
  values="${GEN_DIR}/mc-values-${name}.yaml"

  # One service-mirror controller per link this cluster sources.
  {
    echo "# GENERATED by clusters/05-multicluster.sh"
    echo "controllers:"
    for link in $(links_for_source "$name"); do
      echo "- link:"
      echo "    ref:"
      echo "      name: ${link}"
    done
  } > "$values"

  log "cluster '${name}': installing multicluster extension"
  log "  controllers for links: $(links_for_source "$name" | tr '\n' ' ')"

  linkerd --context="$c" multicluster install \
    -f "$values" \
    | kubectl --context="$c" apply -f - >/dev/null

  ok "  extension applied"
done

log "waiting for gateways to come up"
for name in $(clusters); do
  kubectl --context="$(ctx "$name")" -n linkerd-multicluster \
    rollout status deploy/linkerd-gateway --timeout=180s >/dev/null 2>&1 \
    || warn "cluster '${name}': gateway deployment not ready"
done

# klipper-lb needs a moment to populate .status.loadBalancer.ingress. link-gen
# reads that field, so linking before it is populated produces a broken Link.
log "waiting for gateway LoadBalancer IPs"
for name in $(clusters); do
  lb_ready() {
    [ -n "$(kubectl --context="$(ctx "$1")" -n linkerd-multicluster get svc linkerd-gateway \
            -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null)" ]
  }
  retry 24 5 lb_ready "$name" \
    || die "cluster '${name}': gateway Service never got an EXTERNAL-IP.
Is servicelb enabled? See the --disable list in clusters/01-create-clusters.sh."
  ok "  ${name} gateway at $(kubectl --context="$(ctx "$name")" -n linkerd-multicluster \
        get svc linkerd-gateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
done

# --- create the links -------------------------------------------------------

# Pod-to-pod links: every ordered pair.
for src in $(clusters); do
  for dst in $(clusters); do
    [ "$src" != "$dst" ] || continue

    dst_ip="$(server_ip "$dst")"
    log "link (pod-to-pod): ${src} -> ${dst}  via ${dst_ip}:6443"

    # Remote discovery only: this link has no gateway, so gateway mirroring is
    # pointed at a label nothing carries.
    linkerd --context="$(ctx "$dst")" multicluster link-gen \
      --cluster-name "$dst" \
      --gateway=false \
      --api-server-address "https://${dst_ip}:6443" \
      --selector "$DISABLED_SELECTOR" \
      | kubectl --context="$(ctx "$src")" apply -f - >/dev/null

    ok "  linked"
  done
done

# Gateway links: the contrast case.
for pair in $GATEWAY_LINKS; do
  src="${pair%%:*}"
  dst="${pair##*:}"

  dst_ip="$(server_ip "$dst")"
  lb_ip="$(kubectl --context="$(ctx "$dst")" -n linkerd-multicluster \
    get svc linkerd-gateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"

  log "link (gateway): ${src} -> ${dst} as '${dst}-gw'  gateway LB ${lb_ip}:${GATEWAY_PORT}"

  # Gateway mirroring only (default --selector, exported=true); remote discovery
  # is pointed at a label nothing carries so this link does not also flat-mirror
  # the services the pod-to-pod links already handle.
  #
  # No --gateway-addresses / --gateway-port overrides: link-gen reads the
  # Service's LoadBalancer ingress IP and real ports, which keeps the gateway
  # and probe ports consistent with the mirrored probe Service.
  #
  # --federated-service-selector is ALSO disabled here, and this one matters a
  # great deal. Every gateway source holds TWO links to its target (`east` and
  # `east-gw`). Each link independently contributes matching services to the
  # federated service, so leaving the default on both makes east's three app
  # pods appear TWICE in app-federated: 12 endpoints instead of 9. The
  # baseline silently becomes 25/50/25 instead of 33/33/33, and every
  # traffic-distribution number computed from it is wrong. Exactly one link per
  # target cluster may own federation.
  #
  # This is why adding a gateway source is a two-line change rather than a
  # one-line one: the disable has to come with it. verify/multicluster.sh gates
  # it by asserting endpoint COUNTS and rejecting duplicate endpoint IPs.
  linkerd --context="$(ctx "$dst")" multicluster link-gen \
    --cluster-name "${dst}-gw" \
    --api-server-address "https://${dst_ip}:6443" \
    --remote-discovery-selector "$DISABLED_SELECTOR" \
    --federated-service-selector "mirror.linkerd.io/federated=none" \
    | kubectl --context="$(ctx "$src")" apply -f - >/dev/null

  ok "  linked"
done

# --- verify -----------------------------------------------------------------

log "waiting for service-mirror controllers"
for name in $(clusters); do
  kubectl --context="$(ctx "$name")" -n linkerd-multicluster \
    rollout status deploy --timeout=180s >/dev/null 2>&1 \
    || warn "cluster '${name}': some mirror controllers are slow"
done

echo
log "link inventory"
for name in $(clusters); do
  printf '\n--- %s ---\n' "$name"
  kubectl --context="$(ctx "$name")" -n linkerd-multicluster get links \
    -o custom-columns='LINK:.metadata.name,TARGET_DOMAIN:.spec.targetClusterDomain,GATEWAY:.spec.gatewayAddress' \
    2>/dev/null || echo "(no links)"
done

# Gateway links must report ALIVE. This one is a real signal: the probe runs
# from inside the source cluster, so it exercises the actual data path.
echo
for pair in $GATEWAY_LINKS; do
  src="${pair%%:*}"; dst="${pair##*:}"
  log "gateway liveness: ${src} -> ${dst}-gw"
  gw_alive() {
    linkerd --context="$(ctx "$src")" multicluster gateways 2>/dev/null \
      | awk -v c="${dst}-gw" '$1 == c && $2 == "True" { found = 1 } END { exit !found }'
  }
  retry 12 5 gw_alive || die "gateway link ${dst}-gw never became ALIVE"
  ok "  ${dst}-gw alive"
done

# `linkerd multicluster check` runs from the HOST, but --api-server-address
# points at a Docker-network IP (172.28.x.x) that only containers can reach. So
# "remote cluster access credentials are valid" and "clusters share trust
# anchors" always fail here even when everything is fine -- they are testing the
# host's reachability, not the mesh's.
#
# We do not paper over this: 04-linkerd.sh compares trust anchors directly via
# each cluster's own kubeconfig (a stronger check than going through the
# credential secret), and verify/multicluster.sh asserts that mirrored and
# federated services actually materialise, which is the real functional proof.
echo
log "multicluster check (informational -- see note in this script)"
for name in $(clusters); do
  unexpected="$(linkerd --context="$(ctx "$name")" multicluster check 2>&1 \
    | grep '×' \
    | grep -vE "${KNOWN_HOST_CHECK_FAILURES}|Status check results" \
    || true)"
  if [ -n "$unexpected" ]; then
    warn "  ${name}: unexpected failures beyond the known host-reachability ones:"
    echo "$unexpected"
    failed=1
  else
    ok "  ${name}: only the known host-reachability failures"
  fi
done

[ "${failed:-0}" -eq 0 ] || die "unexpected multicluster check failures"

# Record every node's address on the shared Docker network.
#
# Two callers need this table and they want it for unrelated reasons:
#
#   restore_node_ip   reattaches a partitioned node on the address it left with.
#   cluster_of_ip     resolves a gateway mirror's endpoint -- which is a NODE
#                     address, not a pod IP -- back to the cluster that owns it.
#
# The second is why this is written here rather than only at partition time. A
# gateway-mode measurement taken before any experiment has ever run still has to
# attribute its traffic correctly.
save_node_ips $(clusters)
ok "recorded node addresses for $(clusters | tr '\n' ' ')"

ok "all clusters linked"
