#!/usr/bin/env python3
"""Rebuild all-diagrams.excalidraw by stacking the seven numbered scenes.

    python3 diagrams/build-all.py

Run it after editing any of them. The combined canvas is a convenience copy, and
a convenience copy that is maintained by hand drifts: the last reorder had to be
applied twice and verified twice because of exactly that. Generating it means
there is only ever one place to make a change.

Stdlib only, and it never touches the seven sources -- it reads them, offsets
each scene under a title, and writes the result.
"""
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
NAMES = ["01-steady-state-topology", "02-steady-state-exposure-modes",
         "03-fm1-control-plane", "04-fm2-cluster", "05-fm3-zone-brownout",
         "06-fm4-region", "07-mode-coverage"]
GAP = 90          # vertical space between panels
TITLE_DROP = 40   # title baseline to the top of its scene


def bounds(els):
    xs, ys = [], []
    for e in els:
        x, y = e.get("x", 0), e.get("y", 0)
        if e.get("points"):
            xs += [x + p[0] for p in e["points"]]
            ys += [y + p[1] for p in e["points"]]
        else:
            xs += [x, x + e.get("width", 0)]
            ys += [y, y + e.get("height", 0)]
    return min(xs), min(ys), max(ys)


def title(s, y, i):
    return {"id": f"title{i:02d}aaaaaaaaaaaaaa"[:21], "type": "text",
            "x": 0.0, "y": float(y), "width": len(s) * 12.4, "height": 25.0,
            "angle": 0, "strokeColor": "#151a1c", "backgroundColor": "transparent",
            "fillStyle": "solid", "strokeWidth": 1, "strokeStyle": "solid",
            "roughness": 0, "opacity": 100, "groupIds": [], "frameId": None,
            "roundness": None, "seed": 1000 + i, "version": 1,
            "versionNonce": 2000 + i, "isDeleted": False, "boundElements": [],
            "updated": 1789312439144, "link": None, "locked": False,
            "text": s, "originalText": s, "fontSize": 20, "fontFamily": 3,
            "textAlign": "left", "verticalAlign": "top", "containerId": None,
            "lineHeight": 1.25, "autoResize": True}


def main():
    out, files, cursor = [], {}, 0.0
    for i, name in enumerate(NAMES):
        path = HERE / f"{name}.excalidraw"
        if not path.exists():
            sys.exit(f"missing {path}")
        d = json.loads(path.read_text())
        files.update(d.get("files") or {})
        els = [e for e in d["elements"] if not e.get("isDeleted")]
        left, top, bottom = bounds(els)

        out.append(title(name, cursor, i))
        dx, dy = -left, cursor + TITLE_DROP - top

        # Ids must be unique across the merged canvas, and every reference to
        # them has to move too. Prefixing and truncating is not enough: the
        # scenes generated by to-excalidraw.py name every element after the
        # file, so 39 of 02's ids shared a prefix and collapsed onto one id.
        remap = {e["id"]: f"p{i}e{j:04d}" for j, e in enumerate(els)}

        for e in els:
            e = dict(e)
            e["x"] = e.get("x", 0) + dx
            e["y"] = e.get("y", 0) + dy
            e["id"] = remap[e["id"]]
            for key in ("containerId", "frameId"):
                if e.get(key) in remap:
                    e[key] = remap[e[key]]
            if e.get("boundElements"):
                e["boundElements"] = [
                    {**b, "id": remap.get(b.get("id"), b.get("id"))}
                    for b in e["boundElements"]
                ]
            for key in ("startBinding", "endBinding"):
                b = e.get(key)
                if isinstance(b, dict) and b.get("elementId") in remap:
                    e[key] = {**b, "elementId": remap[b["elementId"]]}
            # `index` must go: each scene carries its own fractional-index
            # sequence, so concatenating seven of them is guaranteed to be
            # non-monotonic, which Excalidraw rejects on load. Dropping it lets
            # Excalidraw assign indices itself, in array order.
            e.pop("index", None)
            out.append(e)
        cursor += TITLE_DROP + (bottom - top) + GAP

    scene = {"type": "excalidraw", "version": 2,
             "source": "diagrams/build-all.py",
             "elements": out,
             "appState": {"gridSize": 20, "gridStep": 5,
                          "gridModeEnabled": False,
                          "viewBackgroundColor": "#ffffff"},
             "files": files}
    dest = HERE / "all-diagrams.excalidraw"
    dest.write_text(json.dumps(scene, indent=2, ensure_ascii=False) + "\n")
    check(scene, dest)
    print(f"{dest.relative_to(HERE.parent)}: {len(out)} elements, "
          f"{len(files)} embedded file(s)")


def check(scene, dest):
    """Refuse to leave behind a scene Excalidraw will not open.

    Both of these have already shipped once. A file that fails to load does not
    say why -- the editor just shows nothing -- so the cheapest place to catch
    it is here, at the moment it is written.
    """
    els = scene["elements"]
    ids = [e["id"] for e in els]
    problems = []

    dupes = {i for i in ids if ids.count(i) > 1}
    if dupes:
        problems.append(f"{len(dupes)} duplicate element id(s), e.g. {sorted(dupes)[0]!r}")

    idx = [e.get("index") for e in els]
    have = sum(1 for i in idx if i is not None)
    if have and have != len(idx):
        problems.append(f"mixed fractional indices: {have} of {len(idx)} elements carry one")
    elif have and any(a >= b for a, b in zip(idx, idx[1:])):
        problems.append("fractional indices are not strictly increasing")

    known = set(ids)
    dangling = 0
    for e in els:
        if e.get("containerId") and e["containerId"] not in known:
            dangling += 1
        for b in e.get("boundElements") or []:
            if b.get("id") and b["id"] not in known:
                dangling += 1
        for key in ("startBinding", "endBinding"):
            b = e.get(key)
            if isinstance(b, dict) and b.get("elementId") and b["elementId"] not in known:
                dangling += 1
    if dangling:
        problems.append(f"{dangling} reference(s) to ids that are not in the scene")

    missing = {e["fileId"] for e in els if e.get("type") == "image"} - set(scene["files"])
    if missing:
        problems.append(f"{len(missing)} image(s) reference a file that is not embedded")

    if problems:
        sys.exit(f"{dest.name} is not loadable:\n  - " + "\n  - ".join(problems))


if __name__ == "__main__":
    main()
